"""Initial schema with automated login

Revision ID: 4fbb45908ac7
Revises: 
Create Date: 2026-01-14 01:35:43.339529

"""
from alembic import op
import sqlalchemy as sa


revision = '4fbb45908ac7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
   
    op.add_column('accounts', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('trading_login_id', sa.String(length=255), nullable=False))
    op.add_column('accounts', sa.Column('encrypted_password', sa.Text(), nullable=True))
    op.add_column('accounts', sa.Column('encrypted_totp_secret', sa.Text(), nullable=False))
    op.add_column('accounts', sa.Column('user_key', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('app_source', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('token_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('accounts', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('accounts', 'api_secret',
               existing_type=sa.TEXT(),
               nullable=True)
    


def downgrade() -> None:
    # ### commands auto generated by Alembic  please adjust guysss! ###
    op.alter_column('accounts', 'api_secret',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('accounts', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('accounts', 'token_generated_at')
    op.drop_column('accounts', 'app_source')
    op.drop_column('accounts', 'user_key')
    op.drop_column('accounts', 'encrypted_totp_secret')
    op.drop_column('accounts', 'encrypted_password')
    op.drop_column('accounts', 'trading_login_id')
    op.drop_column('accounts', 'nickname')
    # ### end Alembic commands ###
