"""Expand models for advanced trades

Revision ID: 7841fc76b4a9
Revises: head_merge_fix
Create Date: 2026-01-29 18:56:31.603747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7841fc76b4a9'
down_revision = 'head_merge_fix'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('multiplier', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('accounts', sa.Column('split_freeze_limit', sa.Integer(), nullable=True))
    op.alter_column('accounts', 'is_validated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('accounts', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_accounts_owner_id', table_name='accounts')
    op.drop_index('idx_accounts_subscription_end', table_name='accounts')
    op.drop_index('idx_accounts_user_id', table_name='accounts')
    op.drop_index('idx_accounts_validated', table_name='accounts')
    op.create_index(op.f('ix_accounts_is_paid'), 'accounts', ['is_paid'], unique=False)
    op.create_index(op.f('ix_accounts_is_validated'), 'accounts', ['is_validated'], unique=False)
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.drop_constraint('fk_accounts_owner_id', 'accounts', type_='foreignkey')
    op.add_column('trades', sa.Column('trigger_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('product', sa.String(length=50), nullable=True))
    op.add_column('trades', sa.Column('target', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('stoploss', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('trailing_stoploss', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('variety', sa.String(length=50), nullable=True))
    op.add_column('trades', sa.Column('validity', sa.String(length=50), nullable=True))
    op.add_column('trades', sa.Column('tag', sa.String(length=100), nullable=True))
    op.add_column('trades', sa.Column('is_amo', sa.Boolean(), nullable=True))
    op.add_column('trades', sa.Column('split_type', sa.String(length=20), nullable=True))
    op.add_column('trades', sa.Column('split_qty', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('multiplier_active', sa.Boolean(), nullable=True))
    op.add_column('trades', sa.Column('group_acc_active', sa.Boolean(), nullable=True))
    op.drop_index('idx_trades_owner_id', table_name='trades')
    op.drop_index('idx_trades_user_id', table_name='trades')
    op.create_index(op.f('ix_trades_owner_id'), 'trades', ['owner_id'], unique=False)
    op.drop_constraint('trades_user_id_fkey', 'trades', type_='foreignkey')
    op.drop_constraint('fk_trades_owner_id', 'trades', type_='foreignkey')
    op.drop_column('trades', 'user_id')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_users_active', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_phone', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_phone', 'users', ['phone_number'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('trades', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_trades_owner_id', 'trades', 'users', ['owner_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('trades_user_id_fkey', 'trades', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_trades_owner_id'), table_name='trades')
    op.create_index('idx_trades_user_id', 'trades', ['user_id'], unique=False)
    op.create_index('idx_trades_owner_id', 'trades', ['owner_id'], unique=False)
    op.drop_column('trades', 'group_acc_active')
    op.drop_column('trades', 'multiplier_active')
    op.drop_column('trades', 'split_qty')
    op.drop_column('trades', 'split_type')
    op.drop_column('trades', 'is_amo')
    op.drop_column('trades', 'tag')
    op.drop_column('trades', 'validity')
    op.drop_column('trades', 'variety')
    op.drop_column('trades', 'trailing_stoploss')
    op.drop_column('trades', 'stoploss')
    op.drop_column('trades', 'target')
    op.drop_column('trades', 'product')
    op.drop_column('trades', 'trigger_price')
    op.create_foreign_key('fk_accounts_owner_id', 'accounts', 'users', ['owner_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_validated'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_paid'), table_name='accounts')
    op.create_index('idx_accounts_validated', 'accounts', ['is_validated'], unique=False)
    op.create_index('idx_accounts_user_id', 'accounts', ['user_id'], unique=False)
    op.create_index('idx_accounts_subscription_end', 'accounts', ['subscription_end_date'], unique=False)
    op.create_index('idx_accounts_owner_id', 'accounts', ['owner_id'], unique=False)
    op.alter_column('accounts', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('accounts', 'is_validated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('accounts', 'split_freeze_limit')
    op.drop_column('accounts', 'multiplier')
    # ### end Alembic commands ###
